#!/bin/sh

alias startx="startx $XINITRC"

alias ls="ls -h --color=auto"

alias grep="grep --color=auto"

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="nocorrect rm -vI"

alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

alias wget="wget --hsts-file="$XDG_CACHE_HOME/wget-hsts""

alias \
    gl="git log --pretty=format:\"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]\"" \
    ga="git add" \
    gap="git add -p" \
    gc="git commit --verbose" \
    gca="git commit -a --verbose" \
    gcm="git commit -m" \
    gcam="git commit -a -m" \
    gm="git commit --amend --verbose" \
    gd="git diff" \
    gds="git diff --stat" \
    gdc="git diff --cached" \
    gs="git status -s" \
    gco="git checkout" \
    gcob="git checkout -b" \
    gp="git push" \

alias \
    e=$EDITOR               \
    se="sudoedit"           \

alias \
    pacman="pacman --color=auto"

alias \
    ll="ls -l"      \
    lla="ls -la"    \
