#!/bin/sh

alias startx="startx $XINITRC"

alias \
    ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \

alias \
    cp="cp -iv" \
	mv="mv -iv" \
	rm="nocorrect rm -vI" \

alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
