#!/bin/sh

# PATH
export PATH="$PATH:$HOME/.local/bin:$HOME/.local/share/script/"

# Basic export
export BROWSER=firefox

# MOZILLA
export LIBVA_DRIVER_NAME="nvidia"
export MOZ_DISABLE_RDD_SANDBOX=1
export MOZ_ENABLE_WAYLAND=1

if hash nvim 2>/dev/null; then
    export EDITOR=nvim
    export MANPAGER='nvim +Man!'
else
    export EDITOR=vim
fi

export TERMINAL=st
export TERM=st-256color

# RUST
export CARGO_HOME=/home/fin/.local/share/cargo

# GNU
export GNUPGHOME=/home/fin/.local/share/gnupg
export GTK2_RC_FILES=/home/fin/.config/gtk-2.0/settings.ini
export GTK_THEME=Adwaita:dark

# Shell
export HISTFILE=/home/fin/.cache/shell/history

# XDG
export HOME=/home/fin
export XAUTHORITY=/home/fin/.cache/Xauthority
export XDG_CACHE_HOME=/home/fin/.cache
export XDG_CONFIG_HOME=/home/fin/.config
export XDG_DATA_HOME=/home/fin/.local/share
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_SEAT=seat0
export XDG_SESSION_CLASS=user
export XDG_SESSION_ID=1
export XDG_SESSION_TYPE=tty
export XDG_STATE_HOME=/home/fin/.local/state
export XDG_VTNR=1
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_RUNTIME_DIR=/run/user/$UID
export XINITRC=/home/fin/.config/X11/xinitrc

# Less
export LESSHISTFILE=-

# R
export R_ENVIRON="$HOME/.config/Renviron"

# zsh
export ZDOTDIR="$HOME/.config/zsh"

# Java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export JAVA_HOME=/usr/lib/jvm/default
export _JAVA_AWT_WM_NONREPARENTING=1


# npm
export npm_config_cache="$HOME/.cache/npm"
export npm_config_userconfig="$HOME/.config/npm/config"

# wget
export WGETRC="$XDG_CONFIG_HOME/wgetrc"

# Things
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

# GO
export GOPATH="$XDG_DATA_HOME"/go

# Android
export PATH="$PATH":~/.local/share/android/emulator
export PATH="$PATH":~/.local/share/android/tools/bin
export PATH="$PATH":~/.local/share/android/tools
export PATH="$PATH":~/.local/share/android/platform-tools
export ANDROID_SDK=~/.local/share/android/sdk
export ANDROID_HOME="$XDG_DATA_HOME"/android


# NVIDIA
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv


# Readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/.pythonrc
export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python

export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc



# Lein
export LEIN_HOME="$XDG_DATA_HOME"/lein


# sqlite
export SQLITE_HISTORY="$XDG_CACHE_HOME"/sqlite_history

# renpy
export RENPY_PATH_TO_SAVES="$XDG_DATA_HOME"/renpy

export ADB_VENDOR_KEYS="$XDG_DATA_HOME"/android/adb_keys

export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default

export QT_QPA_PLATFORM=wayland
