#!/bin/sh
bspc monitor -d 1 2 3 4 5 6

bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true

bspc config border_width                    0
bspc config window_gap                      15

bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_follows_pointer           true

bspc config split_ratio                     0.52
bspc config borderless_monocle              true
bspc config gapless_monocle                 true

bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner


bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a firefox follow=on
