#!/bin/sh
bspc monitor -d 1 2 3 4 5 6

bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true

bspc config border_width                    2
bspc config window_gap                      15
bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#928374"

bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_follows_pointer           false

bspc config split_ratio                     0.52
bspc config borderless_monocle              true
bspc config gapless_monocle                 true

bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner


# ----- Window rules ----- #
#  remove all rules first  #
bspc rule -r "*"

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a firefox follow=on
bspc rule -a firefox:Toolkit sticky=on state=floating border=off
bspc rule -a firefox:Firefox state=floating border=off
