#!/bin/sh

killall polybar
killall picom
killall dunst
killall sxhkd
killall redshift
killall flameshot

# Set default microphone volume
# 30 sounds normal and not bad
pamixer --default-source --set-volume 30

# Status bar
polybar 2>"$HOME"/.config/polybar/log &

# Screenshot
flameshot &

# Notify daemon
dunst &

# Picom for all display
picom -b

# Set wallpaper
setwall &

# Nightmode
/usr/lib/geoclue-2.0/demos/agent &
redshift &

# Keybindings Daemon
sxhkd &

# Set keyboard options
# setxkbmap -layout us -option ctrl:nocaps
xset r rate 280 55 s off -dpms
# xinput set-button-map 11 1 1 1 4 5 6 7

