#!/bin/sh

# DEP: xwallpaper, libnotify

# Full path to input, better for piping into

# Path where wallpaper is linked and set
# Changed if want to store somewhere else
BG_LOCATION=$XDG_CONFIG_HOME/wallpaper
WALLPAPER=""

setWall(){
    if [ "$WALLPAPER" != "" ]
    then
        ln -sf "$WALLPAPER" "$BG_LOCATION"
    fi
    xwallpaper --zoom $BG_LOCATION && \
    notify-send -i $BG_LOCATION "set wallpaper" "$WALLPAPER" -u low || \
    echo "Unexpected Error"

}

if [ $# -eq 1 ]
then
    FULL_PATH=$(readlink -f $1)
    # if directory
    if [ -d "$FULL_PATH" ]
    then
        # Find wallpaper and select 1 @ random
        WALLPAPER=$(find "${FULL_PATH}" -iregex '.*.\(jpg\|jpeg\|png\)' | shuf -n 1)
        # Check if WALLPAPER is not empty
        [ -z "$WALLPAPER" ] && echo "Directory no have immmmmmmage, try again" && exit
    # if file
    elif [ -f "$FULL_PATH" ]
    then
        case $(file -b "$FULL_PATH" | awk '{print $1}') in
            'JPEG'|'PNG'|'JPG')
                WALLPAPER="$FULL_PATH"
                ;;
            *)
                echo "Incorrect filetype , get an actual file with an image :)"
                ;;
        esac
    # If doesn't exist
    else
        echo "Does not exist" && exit
    fi
fi

setWall
